# web server配置
server:
  port: 8080
  servlet:
    context-path: /webapi
#
logging:
  config: classpath:logback.xml



# MySQL数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${IOT_MYSQL_HOST:127.0.0.1}:${IOT_MYSQL_PORT:3306}/iot-cloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Aa0123
    # druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #
      initial-size: 5
      min-idle: 5
      max-active: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #
      filters: stat,wall,slf4j
      filter:
        log4j2:
          enabled: true
          statement-executable-sql-log-enable: true
        stat:
          enabled: true
  #
  mail:
    host: smtp.163.com
    username: cniiot@163.com
    password: VJSTLHTBRHUMIGME
  task:
    scheduling:
      pool:
        size: 1
      thread-name-prefix: iot_cloud_quartz_
      shutdown:
        await-termination: false
        await-termination-period: 10s



#
jwt:
  secret: Aa0123
  expHours: 2
#
hivemq:
  auth-manager:
    username: admin
    password: Aa0123

#
iot:
  cloud:
    backend:
      mqtt-broker:
        url: tcp://127.0.0.1:1883
        clientId: manager:admin
        topics: /device/+/attributes/u,/account/+/+/attributes/u,/device/+/attributes/req/u,/account/+/+/attributes/req/u
        username: admin
        password: Aa0123
        timeout: 10
        keepalive: 30
